name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host ${{ secrets.EC2_IP }}"
        echo "  HostName ${{ secrets.EC2_IP }}"
        echo "  User ${{ secrets.EC2_USERNAME }}"
        echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_IP }} "cd /path/to/your/app && git pull && npm install && pm2 restart all"
